// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using KromaApi.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KromaApi.Infrastructure.Migrations
{
    [DbContext(typeof(KromaDbContext))]
    [Migration("20260919101715_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KromaApi.Domain.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_boards");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_boards_owner_id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("KromaApi.Domain.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_columns");

                    b.HasIndex("BoardId", "Position")
                        .HasDatabaseName("ix_columns_board_id_position");

                    b.ToTable("columns", (string)null);
                });

            modelBuilder.Entity("KromaApi.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("ColumnId", "Position")
                        .HasDatabaseName("ix_cards_column_id_position");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("KromaApi.Domain.Stroke", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("BaseWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("base_width");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<int>("ColorArgb")
                        .HasColumnType("integer")
                        .HasColumnName("color_argb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<float[]>("Points")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("points");

                    b.Property<bool>("SimulatePressure")
                        .HasColumnType("boolean")
                        .HasColumnName("simulate_pressure");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tool");

                    b.HasKey("Id")
                        .HasName("pk_strokes");

                    b.HasIndex("CardId", "CreatedAt")
                        .HasDatabaseName("ix_strokes_card_id_created_at");

                    b.ToTable("strokes", (string)null);
                });

            modelBuilder.Entity("KromaApi.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KromaApi.Domain.Board", b =>
                {
                    b.HasOne("KromaApi.Domain.User", "Owner")
                        .WithMany("Boards")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boards_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KromaApi.Domain.BoardColumn", b =>
                {
                    b.HasOne("KromaApi.Domain.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_columns_boards_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("KromaApi.Domain.Card", b =>
                {
                    b.HasOne("KromaApi.Domain.BoardColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_columns_column_id");

                    b.Navigation("Column");
                });

            modelBuilder.Entity("KromaApi.Domain.Stroke", b =>
                {
                    b.HasOne("KromaApi.Domain.Card", "Card")
                        .WithMany("Strokes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strokes_cards_card_id");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("KromaApi.Domain.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("KromaApi.Domain.BoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("KromaApi.Domain.Card", b =>
                {
                    b.Navigation("Strokes");
                });

            modelBuilder.Entity("KromaApi.Domain.User", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
